spring:
  profiles:
    active: local

server:
  port: 9097
  metrics:
    port: 7001
  api:
    listen:
      host: 0.0.0.0
      port: 3002

camel:
  component: jetty

  springboot:
    main-run-controller: true
    name: mojaloop-simulator-core-connector
    stream-caching-enabled: true

#informed through runtime variable (java -Dbackend.endpoint=http://localhost:3000)
#backend:
#  endpoint: http://localhost:3000

#informed through runtime variable (java -Doutbound.endpoint=http://localhost:3003)
#outbound:
#  endpoint:  http://localhost:3003